
package com.inflectra.spirateam.mylyn.core.internal.services.soap;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * Enables the import and export of data to/from the system
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ImportExport", targetNamespace = "http://www.inflectra.com/SpiraTest/Services/v2.2/", wsdlLocation = "http://localhost/SpiraTeam/Services/v2_2/ImportExport.asmx?WSDL")
public class ImportExport
    extends Service
{

    private final static URL IMPORTEXPORT_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.inflectra.spirateam.mylyn.core.internal.services.soap.ImportExport.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.inflectra.spirateam.mylyn.core.internal.services.soap.ImportExport.class.getResource(".");
            url = new URL(baseUrl, "http://localhost/SpiraTeam/Services/v2_2/ImportExport.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost/SpiraTeam/Services/v2_2/ImportExport.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        IMPORTEXPORT_WSDL_LOCATION = url;
    }

    public ImportExport(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ImportExport() {
        super(IMPORTEXPORT_WSDL_LOCATION, new QName("http://www.inflectra.com/SpiraTest/Services/v2.2/", "ImportExport"));
    }

    /**
     * 
     * @return
     *     returns ImportExportSoap
     */
    @WebEndpoint(name = "ImportExportSoap")
    public ImportExportSoap getImportExportSoap() {
        return super.getPort(new QName("http://www.inflectra.com/SpiraTest/Services/v2.2/", "ImportExportSoap"), ImportExportSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ImportExportSoap
     */
    @WebEndpoint(name = "ImportExportSoap")
    public ImportExportSoap getImportExportSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.inflectra.com/SpiraTest/Services/v2.2/", "ImportExportSoap"), ImportExportSoap.class, features);
    }

}
